In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import polars as pl
import pyreadstat as prs
import seaborn as sns

In [2]:
def extract_from_dict_key(dict_, search_word):
    for key, val in dict_.items():
        if search_word.lower() in val.lower() or search_word.lower() in key.lower():
            print(f"{key}: {val}")

In [3]:
df, meta = prs.read_dta(
    "/Users/dmiri/PythonProjects/jupyterlab/data/data/RLMS_IND_1994_2025_eng.dta"
)
df

,id_w,idind,year,redid_i,id_i,id_h,origsm,inwgt,region,psu,...,s6,s7,s1_1_l,s1_2_l,s2_l,s3_l,s4_l,s5_l,s6_l,s7_l
0,5.0,1.0,1994.0,101.0,1.001010e+05,1001.0,1.0,0.917995,1.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,5.0,2.0,1994.0,102.0,1.001020e+05,1001.0,1.0,1.047906,1.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,5.0,3.0,1994.0,201.0,1.002010e+05,1002.0,1.0,0.983448,1.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,5.0,4.0,1994.0,202.0,1.002020e+05,1002.0,1.0,0.985150,1.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,5.0,1994.0,203.0,1.002030e+05,1002.0,1.0,0.966657,1.0,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
474595,34.0,59403.0,2025.0,568701.0,1.429001e+09,14290014.0,1.0,0.742500,142.0,3.0,...,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474596,34.0,59404.0,2025.0,568702.0,1.429001e+09,14290014.0,1.0,1.059966,142.0,3.0,...,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474597,34.0,59406.0,2025.0,568704.0,1.429001e+09,14290014.0,1.0,0.939756,142.0,3.0,...,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474598,34.0,59407.0,2025.0,568705.0,1.429001e+09,14290014.0,1.0,1.078859,142.0,3.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
474599,34.0,59412.0,2025.0,542601.0,1.429002e+09,14290017.0,1.0,0.742500,142.0,3.0,...,3.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
extract_from_dict_key(meta.column_names_to_labels, "pension")

j73:  RECEIVES A PENSION?
j74:  TYPE OF PENSION RECEIVED
j74_1:  PENSION FOR RETIREMENT?
j74_2:  PENSION FOR DISABILITY?
j74_3:  PENSION FOR YEARS OF SERVICE?
j74_4:  PENSION FOR YEARS OF SERVICE?
j74_5:  PENSION FOR MILITARY SERVICE?
j74_6:  PENSION FOR SOCIAL SECURITY?
j74_7:  PENSION FOR OTHER?
j73_1m:  WHEN GRANTED PENSION? MONTH?
j73_1y:  WHEN GRANTED PENSION? YEAR?
j73_2:  EMPLOYMENT OR STATE PENSION?
j74a:  TYPE OF PENSION RECEIVED--#1
j74b:  TYPE OF PENSION RECEIVED--#2
j259:  EXPERIENCE FOR EARLY REGISTRATION PENSION--FULL YEARS
j74_1a:  TYPE OF PENSION RECEIVED--#1
j74_1b:  TYPE OF PENSION RECEIVED--#2
j74_1c:  TYPE OF PENSION RECEIVED--#3
j74_22:  TRANSITION TO ANOTHER KIND OF LABOUR PENSION
j74_23:  KIND OF LABOUR PENSION
j73_1am:  WHEN GRANTED THIS PENSION?--MONTH
j73_1ay:  WHEN GRANTED THIS PENSION?--YEAR
j238:  EARNINGS AS A BASE FOR CALCULATION OF PENSION?
j241:  HOW MANY TIMES DID YOU VISIT THE PENSION FUND?
j242a:  THE DURATION OF VISIT IN PENSION FUND OFFICE HOURS
j242b:  THE DURATION OF VISIT IN PENSION FUND OFFICE MINUTES
j243m:  TIME SINCE FIRST VISIT TO PENSION FUND TILL THE MONMENT GOT A PENSION CERTIFICA
j243d:  TIME SINCE FIRST VISIT TO PENSION FUND TILL THE MONMENT GOT A PENSION CERTIFICA
j244:  Have you had your pension reassessed since 2002?
j245:  Was the reassessment made based on the information available in the Pension Fun
j246:  How many times had you have to visit a Pension Fund of Russia office while your
j247a:  How much time on average did it take to resolve issues at a Pension Fund of Rus
j247b:  How much time on average did it take to resolve issues at a Pension Fund of Rus
j248a:  How long does it take you to get to your Pension Fund office? (hours)
j248b:  How long does it take you to get to your Pension Fund office? (minutes)
j362:  SOCIAL SURCHARGE TO PENSION
j249:  Please, tell me how satisfied are you with the work of your Pension Fund office
j250:  In 2007, some territorial bodies of the Pension Fund were reorganized. Do peopl
j75:  RECEIVED PENSION IN LAST 30 DAYS?
j363:  PENSION AMOUNT IN LAST 30 DAYS PLUS BENEFITS
j453_1:  The most important way to improve the situation in the pension system in the fu
j453_2:  The second way to improve the situation in the pension system in the future, wh
j76:  PENSION AMOUNT IN LAST 30 DAYS--A.J76
j76_1:  GOVERNMENT PENSION OWED?
j133_5:  RETIREMENT FUNDS--ADD. PENSION
j134:  KNOWS OF PENSION CHOICE DEADLINE
j135:  PENSION FUND MANAGER
j187:  Do you have a pension insurance card, that is, a pension insurance certificate?
j146:  Since 2002 in Russia new rules for calculating pensions have been introduced. D
j147_1:  Do you get information about pension reform from TV programs?
j147_2:  Do you get information about pension reform from articles in newspapers, magazi
j147_3:  Do you get information about pension reform from radio?
j147_4:  Do you get information about pension reform from internet?
j147_5:  Do you get information about pension reform from relatives, friends?
j147_6:  Do you get information about pension reform at work?
j147_7:  Do you get information about pension reform from other sources?
j147_10:  Do you get information about pension reform from Mailing of notifications of th
j147_8:  Do you receive information about pension reform from special publications issue
j147_9:  Do you receive information about pension reform from advertising materials of p
j149:  INFORMATION LETTERS FROM THE PENSION FUND OF RUSSIA
j150_0:  Let`s talk about the insurance component of your future labor pension. Tell me,
j152:  Who have you entrusted to manage the funded component of your labor pension?
j251:  Who have you entrusted to manage the funded component of your labor pension in
j153_1:  Why did you entrust funds of the funded component of your labor pension to this
j153_2:  Why did you entrust funds of the funded component of your labor pension to this
j153_3:  Why did you entrust funds of the funded component of your labor pension to this
j153_4:  Why did you entrust funds of the funded component of your labor pension to this
j153_5:  Why did you entrust funds of the funded component of your labor pension to this
j153_6:  Why did you entrust funds of the funded component of your labor pension to this
j153_7:  Why did you entrust funds of the funded component of your labor pension to this
j156:  Who exactly will you trust to manage the funded component of your labor pension
j252:  When you retire, what share of your total pension do you think will be the fund
j159:  Do you know the approximate amount of your pension?
j160:  Do you know how to calculate the amount of your pension?
j264:  Are you ready to voluntary save money in such an individual pension savings acc
j257:  Who would you entrust to manage your voluntary pension savings in this case?
j267:  Do you know that if a person of retirement age doesn`t apply for a pension and
j274_1:  Do you agree: if you work for 30 years you will be entitled to a full pension,
j274_2:  Do you support the proposal that in order to pay people decent pensions, it`s n
j274_3:  Do you agree that when calculating pensions periods when a person didn`t work f
j274_4:  Do you support the proposal that in order to pay decent pensions, it is necessa
j198_1:  CARD FOR TRANSFERING SALARY_PENSION
j525_7:  In your opinion how fair or unfair are pension provision and social benefits in
n65:  USE MC_TRANSFER MONEY TO CUMULATIVE PART OF PENSION OR SPEND IT FOR IMPROV OF L
n66_1:  YOU LEAVE MONEY OF MC IN CUMULATIVE PART OF PENSION BEFORE PENSION AGE
n126_1:  YOU WILL DIRECT MEANS OF THE PARENT CAPITAL IN THE FUNDED PART OF THE PENSION?

In [5]:
df_pl = pl.from_pandas(df)
df_pl

shape: (474_600, 4_283)
┌──────┬─────────┬────────┬──────────┬───┬──────┬──────┬──────┬──────┐
│ id_w ┆ idind   ┆ year   ┆ redid_i  ┆ … ┆ s4_l ┆ s5_l ┆ s6_l ┆ s7_l │
│ ---  ┆ ---     ┆ ---    ┆ ---      ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---  │
│ f64  ┆ f64     ┆ f64    ┆ f64      ┆   ┆ f64  ┆ f64  ┆ f64  ┆ f64  │
╞══════╪═════════╪════════╪══════════╪═══╪══════╪══════╪══════╪══════╡
│ 5.0  ┆ 1.0     ┆ 1994.0 ┆ 101.0    ┆ … ┆ null ┆ null ┆ null ┆ null │
│ 5.0  ┆ 2.0     ┆ 1994.0 ┆ 102.0    ┆ … ┆ null ┆ null ┆ null ┆ null │
│ 5.0  ┆ 3.0     ┆ 1994.0 ┆ 201.0    ┆ … ┆ null ┆ null ┆ null ┆ null │
│ 5.0  ┆ 4.0     ┆ 1994.0 ┆ 202.0    ┆ … ┆ null ┆ null ┆ null ┆ null │
│ 5.0  ┆ 5.0     ┆ 1994.0 ┆ 203.0    ┆ … ┆ null ┆ null ┆ null ┆ null │
│ …    ┆ …       ┆ …      ┆ …        ┆ … ┆ …    ┆ …    ┆ …    ┆ …    │
│ 34.0 ┆ 59403.0 ┆ 2025.0 ┆ 568701.0 ┆ … ┆ null ┆ null ┆ null ┆ null │
│ 34.0 ┆ 59404.0 ┆ 2025.0 ┆ 568702.0 ┆ … ┆ null ┆ null ┆ null ┆ null │
│ 34.0 ┆ 59406.0 ┆ 2025.0 ┆ 568704.0 ┆ … ┆ null ┆ null ┆ null ┆ null │
│ 34.0 ┆ 59407.0 ┆ 2025.0 ┆ 568705.0 ┆ … ┆ null ┆ null ┆ null ┆ null │
│ 34.0 ┆ 59412.0 ┆ 2025.0 ┆ 542601.0 ┆ … ┆ null ┆ null ┆ null ┆ null │
└──────┴─────────┴────────┴──────────┴───┴──────┴──────┴──────┴──────┘

In [6]:
farmers_df = df_pl.with_columns(
    (
        (pl.col("j90") == 10)
        | ((pl.col("j4_1") == 8) & (pl.col("j11").is_in([2, 3, 4])))
        | (
            (pl.col("j56") == 1)
            & ((pl.col("j60_4a2") == 1) | (pl.col("j60_4a3") == 1))
            & (pl.col("j57") > 10_000)
        )
    ).alias("is_farmer")
).with_columns(
    pl.when(pl.col("is_farmer") == True).then(1).otherwise(0).alias("is_farmer")
)
farmers_df = farmers_df.filter(pl.col("year") == 2025)
farmers_df

shape: (16_176, 4_284)
┌──────┬─────────┬────────┬──────────┬───┬──────┬──────┬──────┬───────────┐
│ id_w ┆ idind   ┆ year   ┆ redid_i  ┆ … ┆ s5_l ┆ s6_l ┆ s7_l ┆ is_farmer │
│ ---  ┆ ---     ┆ ---    ┆ ---      ┆   ┆ ---  ┆ ---  ┆ ---  ┆ ---       │
│ f64  ┆ f64     ┆ f64    ┆ f64      ┆   ┆ f64  ┆ f64  ┆ f64  ┆ i32       │
╞══════╪═════════╪════════╪══════════╪═══╪══════╪══════╪══════╪═══════════╡
│ 34.0 ┆ 25025.0 ┆ 2025.0 ┆ 131301.0 ┆ … ┆ null ┆ null ┆ null ┆ 0         │
│ 34.0 ┆ 25026.0 ┆ 2025.0 ┆ 131302.0 ┆ … ┆ null ┆ null ┆ null ┆ 0         │
│ 34.0 ┆ 30114.0 ┆ 2025.0 ┆ 131303.0 ┆ … ┆ null ┆ null ┆ null ┆ 0         │
│ 34.0 ┆ 25031.0 ┆ 2025.0 ┆ 131401.0 ┆ … ┆ null ┆ null ┆ null ┆ 0         │
│ 34.0 ┆ 25032.0 ┆ 2025.0 ┆ 131501.0 ┆ … ┆ null ┆ null ┆ null ┆ 0         │
│ …    ┆ …       ┆ …      ┆ …        ┆ … ┆ …    ┆ …    ┆ …    ┆ …         │
│ 34.0 ┆ 59403.0 ┆ 2025.0 ┆ 568701.0 ┆ … ┆ null ┆ null ┆ null ┆ 0         │
│ 34.0 ┆ 59404.0 ┆ 2025.0 ┆ 568702.0 ┆ … ┆ null ┆ null ┆ null ┆ 0         │
│ 34.0 ┆ 59406.0 ┆ 2025.0 ┆ 568704.0 ┆ … ┆ null ┆ null ┆ null ┆ 0         │
│ 34.0 ┆ 59407.0 ┆ 2025.0 ┆ 568705.0 ┆ … ┆ null ┆ null ┆ null ┆ 0         │
│ 34.0 ┆ 59412.0 ┆ 2025.0 ┆ 542601.0 ┆ … ┆ null ┆ null ┆ null ┆ 0         │
└──────┴─────────┴────────┴──────────┴───┴──────┴──────┴──────┴───────────┘

In [7]:
farmers_df["is_farmer"].value_counts()

shape: (2, 2)
┌───────────┬───────┐
│ is_farmer ┆ count │
│ ---       ┆ ---   │
│ i32       ┆ u32   │
╞═══════════╪═══════╡
│ 0         ┆ 16084 │
│ 1         ┆ 92    │
└───────────┴───────┘

In [20]:
df_2025_complete = farmers_df.to_pandas()
df_2025_complete["gender"] = df_2025_complete["h5"].replace(
    meta.variable_value_labels["h5"]
)
df_2025_complete["is_female"] = np.where(df_2025_complete["gender"] == "FEMALE", 1, 0)
df_2025_complete["diplom"] = df_2025_complete["diplom"].replace(
    meta.variable_value_labels["diplom"]
)
df_2025_complete["marst"] = df_2025_complete["marst"].replace(
    meta.variable_value_labels["marst"]
)
df_2025_complete["region"] = df_2025_complete["region"].replace(
    meta.variable_value_labels["region"]
)
df_2025_complete["i3"] = df_2025_complete["i3"].replace(
    meta.variable_value_labels["i3"]
)
df_2025_complete["j90"] = df_2025_complete["j90"].replace(
    meta.variable_value_labels["j90"]
)
df_2025_complete["j4_1"] = df_2025_complete["j4_1"].replace(
    meta.variable_value_labels["j4_1"]
)
df_2025_complete["j60_4a2"] = df_2025_complete["j60_4a2"].replace(
    meta.variable_value_labels["j60_4a2"]
)
df_2025_complete = df_2025_complete.rename(
    columns={
        "j60": "total_income_last30_days",
        'j10': 'job1_wage',
        'j40':'job2_wage',
        'j57':'iea_income',
        'j363': 'pension_benefit', 
        "j72_172": "children_num",
        "i3": "settlement_type_born",
        "h3": "family_id",
        "h4": "family_member_id",
        "j90": "primary_occupation",
        "j4_1": "industry_job1",
        'j35_1': 'industry_job2',
        "j60_4a2": "raised_and_sell_crops",
        "j8": "ow",
        "j38": "ow2",
        "j59": "ow_iea",
        "j1_1_1": "job_satisfaction",
        'j1_1_3': 'satisfaction_w_pay',
        'j1_1_6': 'satisfaction_w_ow',
        
    }
)
df_2025_complete = df_2025_complete[
    [
        "family_id",
        "family_member_id",
        "total_income_last30_days",
        'job1_wage',
        'job2_wage',
        'iea_income',
        'pension_benefit',
        "age",
        "gender",
        "is_female",
        "diplom",
        "marst",
        "children_num",
        "settlement_type_born",
        "region",
        "primary_occupation",
        "industry_job1",
        'industry_job2',
        "raised_and_sell_crops",
        "ow",
        "ow2",
        "ow_iea",
        'job_satisfaction',
        'satisfaction_w_pay',
        'satisfaction_w_ow',
        "is_farmer",
        "inwgt",
    ]
]
df_2025_complete["total_income_last30_days"] = np.where(
    df_2025_complete["total_income_last30_days"].isin(
        [99999999.0, 99999998.0, 99999997.0]
    ),
    0,
    df_2025_complete["total_income_last30_days"],
)
df_2025_complete["ow"] = np.where(
    df_2025_complete["ow"].isin([99999999.0, 99999998.0, 99999997.0]),
    np.nan,
    df_2025_complete["ow"],
).astype(float)
df_2025_complete["ow2"] = np.where(
    df_2025_complete["ow2"].isin([99999999.0, 99999998.0, 99999997.0]),
    np.nan,
    df_2025_complete["ow2"],
).astype(float)
df_2025_complete["ow_iea"] = np.where(
    df_2025_complete["ow_iea"].isin([99999999.0, 99999998.0, 99999997.0]),
    np.nan,
    df_2025_complete["ow_iea"],
).astype(float)
df_2025_complete["hours_worked"] = (
    df_2025_complete[["ow", "ow2", "ow_iea"]].bfill(axis=1).iloc[:, 0]
)


df_2025_complete

,family_id,family_member_id,total_income_last30_days,job1_wage,job2_wage,iea_income,pension_benefit,age,gender,is_female,...,raised_and_sell_crops,ow,ow2,ow_iea,job_satisfaction,satisfaction_w_pay,satisfaction_w_ow,is_farmer,inwgt,hours_worked
0,13.0,1.0,40000.0,40000.0,NaN,NaN,NaN,48.5,MALE,0,...,No,175.0,NaN,NaN,2.0,4.0,2.0,0,0.000000,175.0
1,13.0,2.0,0.0,NaN,NaN,NaN,NaN,44.5,FEMALE,1,...,No,NaN,NaN,NaN,NaN,NaN,NaN,0,0.000000,NaN
2,13.0,3.0,0.0,NaN,NaN,NaN,NaN,18.0,FEMALE,1,...,No,NaN,NaN,NaN,NaN,NaN,NaN,0,0.000000,NaN
3,14.0,1.0,31000.0,NaN,NaN,NaN,26000.0,76.5,FEMALE,1,...,No,NaN,NaN,NaN,NaN,NaN,NaN,0,0.742500,NaN
4,16.0,1.0,35000.0,35000.0,NaN,NaN,NaN,47.5,FEMALE,1,...,No,154.0,NaN,NaN,1.0,3.0,1.0,0,0.867410,154.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16171,90014.0,1.0,20100.0,NaN,NaN,NaN,20100.0,66.5,FEMALE,1,...,No,NaN,NaN,NaN,NaN,NaN,NaN,0,0.742500,NaN
16172,90014.0,2.0,70000.0,70000.0,NaN,NaN,NaN,38.0,FEMALE,1,...,No,168.0,NaN,NaN,1.0,2.0,2.0,0,1.059966,168.0
16173,90014.0,4.0,0.0,NaN,NaN,NaN,NaN,17.0,FEMALE,1,...,No,NaN,NaN,NaN,NaN,NaN,NaN,0,0.939756,NaN
16174,90014.0,5.0,NaN,NaN,NaN,NaN,NaN,9.0,FEMALE,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,1.078859,NaN
16175,90017.0,1.0,20100.0,NaN,NaN,NaN,16686.0,73.5,FEMALE,1,...,No,NaN,NaN,NaN,NaN,NaN,NaN,0,0.742500,NaN

In [21]:
df_2025_complete["is_farmer"].value_counts()

is_farmer
0    16084
1       92
Name: count, dtype: int64

In [22]:
def reconstruct_families(
    df, member_col="family_member_num", new_family_col="new_family_id"
):
    """
    Reconstruct family groupings based on member enumeration resets.

    Parameters:
    -----------
    df : pandas.DataFrame
        DataFrame containing the enumerated family members
    member_col : str
        Column name with the enumerated family member numbers
    new_family_col : str
        Name for the new reconstructed family ID column

    Returns:
    --------
    pandas.DataFrame with new family_id and family_size columns
    """
    df = df.copy()

    # Detect where a new family starts:
    # A reset occurs when current value <= previous value
    # First row always starts a new family
    is_new_family = (df[member_col].diff() <= 0) | (df[member_col].diff().isna())

    # Cumulative sum creates a new group id for each reset
    df[new_family_col] = is_new_family.cumsum()

    # Compute total members per family
    family_sizes = df.groupby(new_family_col)[member_col].transform("size")
    df["family_size"] = family_sizes

    return df

In [23]:
df_2025_complete = reconstruct_families(
    df_2025_complete, member_col="family_member_id", new_family_col="family_id_imputed"
)
df_2025_complete

,family_id,family_member_id,total_income_last30_days,job1_wage,job2_wage,iea_income,pension_benefit,age,gender,is_female,...,ow2,ow_iea,job_satisfaction,satisfaction_w_pay,satisfaction_w_ow,is_farmer,inwgt,hours_worked,family_id_imputed,family_size
0,13.0,1.0,40000.0,40000.0,NaN,NaN,NaN,48.5,MALE,0,...,NaN,NaN,2.0,4.0,2.0,0,0.000000,175.0,1,3
1,13.0,2.0,0.0,NaN,NaN,NaN,NaN,44.5,FEMALE,1,...,NaN,NaN,NaN,NaN,NaN,0,0.000000,NaN,1,3
2,13.0,3.0,0.0,NaN,NaN,NaN,NaN,18.0,FEMALE,1,...,NaN,NaN,NaN,NaN,NaN,0,0.000000,NaN,1,3
3,14.0,1.0,31000.0,NaN,NaN,NaN,26000.0,76.5,FEMALE,1,...,NaN,NaN,NaN,NaN,NaN,0,0.742500,NaN,2,1
4,16.0,1.0,35000.0,35000.0,NaN,NaN,NaN,47.5,FEMALE,1,...,NaN,NaN,1.0,3.0,1.0,0,0.867410,154.0,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16171,90014.0,1.0,20100.0,NaN,NaN,NaN,20100.0,66.5,FEMALE,1,...,NaN,NaN,NaN,NaN,NaN,0,0.742500,NaN,5822,4
16172,90014.0,2.0,70000.0,70000.0,NaN,NaN,NaN,38.0,FEMALE,1,...,NaN,NaN,1.0,2.0,2.0,0,1.059966,168.0,5822,4
16173,90014.0,4.0,0.0,NaN,NaN,NaN,NaN,17.0,FEMALE,1,...,NaN,NaN,NaN,NaN,NaN,0,0.939756,NaN,5822,4
16174,90014.0,5.0,NaN,NaN,NaN,NaN,NaN,9.0,FEMALE,1,...,NaN,NaN,NaN,NaN,NaN,0,1.078859,NaN,5822,4
16175,90017.0,1.0,20100.0,NaN,NaN,NaN,16686.0,73.5,FEMALE,1,...,NaN,NaN,NaN,NaN,NaN,0,0.742500,NaN,5823,1

In [24]:
df_2025_complete[df_2025_complete["is_farmer"] == 1]

,family_id,family_member_id,total_income_last30_days,job1_wage,job2_wage,iea_income,pension_benefit,age,gender,is_female,...,ow2,ow_iea,job_satisfaction,satisfaction_w_pay,satisfaction_w_ow,is_farmer,inwgt,hours_worked,family_id_imputed,family_size
746,150.0,4.0,45000.0,NaN,NaN,25000.0,20000.0,55.0,FEMALE,1,...,NaN,180.0,NaN,NaN,NaN,1,0.867410,180.0,273,3
1331,325.0,3.0,50000.0,50000.0,NaN,NaN,NaN,38.0,MALE,0,...,NaN,NaN,2.0,1.0,1.0,1,1.492625,168.0,479,4
1659,224.0,1.0,50000.0,40000.0,NaN,NaN,NaN,56.5,MALE,0,...,NaN,NaN,4.0,4.0,1.0,1,1.034439,240.0,592,2
2028,223.0,1.0,40000.0,NaN,NaN,40000.0,NaN,48.0,FEMALE,1,...,NaN,NaN,NaN,NaN,NaN,1,0.833769,NaN,748,3
2029,223.0,2.0,50000.0,NaN,NaN,50000.0,NaN,53.0,MALE,0,...,NaN,NaN,NaN,NaN,NaN,1,1.034439,NaN,748,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11319,171.0,4.0,60000.0,NaN,NaN,60000.0,NaN,23.5,MALE,0,...,NaN,NaN,NaN,NaN,NaN,1,0.979740,NaN,4045,9
11365,201.0,1.0,30000.0,30000.0,NaN,NaN,NaN,44.5,FEMALE,1,...,NaN,NaN,2.0,2.0,2.0,1,1.062026,90.0,4058,4
11366,201.0,2.0,90000.0,90000.0,NaN,NaN,NaN,47.5,MALE,0,...,NaN,NaN,2.0,2.0,1.0,1,1.034439,224.0,4058,4
13006,4036.0,3.0,45000.0,NaN,NaN,45000.0,NaN,19.5,FEMALE,1,...,NaN,NaN,NaN,NaN,NaN,1,0.939756,NaN,4632,4
14044,11.0,2.0,93500.0,46000.0,NaN,30000.0,17500.0,68.5,FEMALE,1,...,NaN,40.0,2.0,4.0,3.0,1,0.000000,264.0,5031,4

In [25]:
df_2025_complete[df_2025_complete["is_farmer"] == 1][
    "primary_occupation"
].value_counts()

primary_occupation
Working NOT at an enterprise, organization, collective farm, state farm, or coop    62
An entrepreneur                                                                     11
A farmer                                                                             5
Working at an enterprise, organization, collective farm, state farm, or cooperat     5
Temporarily not employed for other reasons and not looking for a job                 4
Retired and not working                                                              2
A housewife, caring for other family members, raising children                       2
Full-time University student                                                         1
Name: count, dtype: int64

In [26]:
df_2025_complete[df_2025_complete["is_farmer"] == 1].isna().sum()

family_id                    0
family_member_id             0
total_income_last30_days     0
job1_wage                   13
job2_wage                   91
iea_income                  77
pension_benefit             85
age                          0
gender                       0
is_female                    0
diplom                       0
marst                        0
children_num                21
settlement_type_born        65
region                       0
primary_occupation           0
industry_job1               11
industry_job2               91
raised_and_sell_crops        0
ow                          33
ow2                         91
ow_iea                      86
job_satisfaction            11
satisfaction_w_pay          11
satisfaction_w_ow           11
is_farmer                    0
inwgt                        0
hours_worked                30
family_id_imputed            0
family_size                  0
dtype: int64

In [28]:
df_2025_complete["raised_and_sell_crops"].value_counts()

raised_and_sell_crops
No     13453
Yes      224
Name: count, dtype: int64

In [29]:
df_2025_complete["children_num"] = df_2025_complete["children_num"].fillna(0)
df_2025_complete["total_income_last30_days"] = df_2025_complete[
    "total_income_last30_days"
].fillna(0)
df_2025_complete["diplom"] = df_2025_complete["diplom"].fillna("NO ANSWER")
df_2025_complete["marst"] = df_2025_complete["marst"].fillna("Never married")
df_2025_complete["primary_occupation"] = df_2025_complete["primary_occupation"].fillna(
    "Does not work"
)
df_2025_complete["raised_and_sell_crops"] = df_2025_complete[
    "raised_and_sell_crops"
].fillna("No")
df_2025_complete

,family_id,family_member_id,total_income_last30_days,job1_wage,job2_wage,iea_income,pension_benefit,age,gender,is_female,...,ow2,ow_iea,job_satisfaction,satisfaction_w_pay,satisfaction_w_ow,is_farmer,inwgt,hours_worked,family_id_imputed,family_size
0,13.0,1.0,40000.0,40000.0,NaN,NaN,NaN,48.5,MALE,0,...,NaN,NaN,2.0,4.0,2.0,0,0.000000,175.0,1,3
1,13.0,2.0,0.0,NaN,NaN,NaN,NaN,44.5,FEMALE,1,...,NaN,NaN,NaN,NaN,NaN,0,0.000000,NaN,1,3
2,13.0,3.0,0.0,NaN,NaN,NaN,NaN,18.0,FEMALE,1,...,NaN,NaN,NaN,NaN,NaN,0,0.000000,NaN,1,3
3,14.0,1.0,31000.0,NaN,NaN,NaN,26000.0,76.5,FEMALE,1,...,NaN,NaN,NaN,NaN,NaN,0,0.742500,NaN,2,1
4,16.0,1.0,35000.0,35000.0,NaN,NaN,NaN,47.5,FEMALE,1,...,NaN,NaN,1.0,3.0,1.0,0,0.867410,154.0,3,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16171,90014.0,1.0,20100.0,NaN,NaN,NaN,20100.0,66.5,FEMALE,1,...,NaN,NaN,NaN,NaN,NaN,0,0.742500,NaN,5822,4
16172,90014.0,2.0,70000.0,70000.0,NaN,NaN,NaN,38.0,FEMALE,1,...,NaN,NaN,1.0,2.0,2.0,0,1.059966,168.0,5822,4
16173,90014.0,4.0,0.0,NaN,NaN,NaN,NaN,17.0,FEMALE,1,...,NaN,NaN,NaN,NaN,NaN,0,0.939756,NaN,5822,4
16174,90014.0,5.0,0.0,NaN,NaN,NaN,NaN,9.0,FEMALE,1,...,NaN,NaN,NaN,NaN,NaN,0,1.078859,NaN,5822,4
16175,90017.0,1.0,20100.0,NaN,NaN,NaN,16686.0,73.5,FEMALE,1,...,NaN,NaN,NaN,NaN,NaN,0,0.742500,NaN,5823,1

In [30]:
df_2025_complete["total_income_last30_days"].sort_values(ascending=False).unique()[:3]

array([2000000., 1526000., 1420975.])

In [31]:
df_2025_complete["hours_worked"].sort_values(ascending=False).unique()[:3]

array([720., 540., 480.])

In [32]:
df_2025_complete.isna().sum()

family_id                       0
family_member_id                0
total_income_last30_days        0
job1_wage                    8658
job2_wage                   15921
iea_income                  15621
pension_benefit             11513
age                             0
gender                          0
is_female                       0
diplom                          0
marst                           0
children_num                    0
settlement_type_born        10608
region                          0
primary_occupation              0
industry_job1                8455
industry_job2               15896
raised_and_sell_crops           0
ow                           9669
ow2                         15942
ow_iea                      15795
job_satisfaction             8455
satisfaction_w_pay           8455
satisfaction_w_ow            8455
is_farmer                       0
inwgt                           0
hours_worked                 9361
family_id_imputed               0
family_size                     0
dtype: int64

In [34]:
df_2025_complete.to_parquet("../data/working_set1.parquet", index=False)